services:
  coturn:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Moscow
      - TURN_EXTERNAL_IP=${TURN_EXTERNAL_IP}
      - TURN_SERVER_NAME=${TURN_SERVER_NAME}
      - TURN_SECRET=${TURN_SECRET}
    volumes:
      - /etc/nginx/ssl/stunturn.devshit.ru_P256/:/etc/coturn/certs/
