log-file=stdout
external-ip=176.124.201.211
listening-ip=176.124.201.211
fingerprint
verbose
lt-cred-mech
user=turn:9jxtlyfasz2zqzfmtdv1a8d4r9bvaq7k
no-cli
server-name=stunturn.devshit.ru
realm=stunturn.devshit.ru
listening-port=3478
tls-listening-port=5349
min-port=49152
max-port=65535
cert=/etc/coturn/certs/fullchain.cer
pkey=/etc/coturn/certs/private.key
